
* how to build repo 
    cd lib/
    pip install or conda install 
    python make.py 
    cd ..
    python -m SimpleHttpServer
* TODO todo
** TODO make fullstory work
** make domain names work
** TODO make module work more better 8pm
** whats your favorite thing in thing world ?
*** whats your favorite research paper
*** whats your favorite scientist?
*** what book would you want everyone in the world to read





use static site like soul-wire.co.uk 
so it always works and anyone can contrib an observable 
or hand written page one folder at a time 

react-server-side-rendering - reusable head + styles

each folder one page 
table 

only need SEO + reusable styles on 
make users use a imported stylesheet with tailwind 
and basics that hides unnnecesary stuff from obs

workflow -> 
learn react and obfuscated garbage
include a script tag with a src="../toggle-able-header-at-top.js"
append a div at top
append styles 

book has to be server side progressive enhancement


export 

1 million notebooks from observable from all stream 
1 billion users will appreciate your convert-obs-to-interactive-shader-book.js

use iframes for now 

add a make file or a node script or a python script that adds SEO stuff + link backwards to table of contents 





this wiki book is designed specifically to unbundle governments, restore dignity to the individual, implement UBI, build future-hollistic-carbon-zero cities, and improve education so children can leapfrog and start researching the best of the frontier of science and art

tell governments how to upgrade their consciousness by co-inventing antennas
for public conscumption of AGI + telepathy


* put images here

[wikipedia.com](hello.md)

0. do not do that which create aversion - grow towards light
1. unification + federated identity + opt-in-out communication morpheus focus groups
2. water slides and free time for everyone + robots and AI+technology for limitless productivity 
    how does technology enhance capabilities of the mind ? - speech to text - do what i mean
3. harmony with nature rather than working against - equilibrium etc


1. pixel grid - magi system
2. morpheus focus groups - webgpu particle system - (webgl prototype) (hierarchy, circle, sierpinsiki pyramid, megaphone)
3. world - satellitle orbit - rotate saetellitle around planet to relay thoughts in a loop around people .-0-.
4. finish these all in one day then go back to framework
5.  diagrams for "civic control center" 
6. maps with emotional valence of every citizen - see disturbance in the force - robot baby sitter = people watching map 
7. submind diagram
8. mind is a curtain - rube goldberg machine behind 
9. wheel of depedendent origination sputtering thoughts
10. stagaltite diagram
11. plant growing towards light
12. synapses - chain of dependent electrical reactions 
13. subminds agreeing = bubbles
14. glass of water

compute shaders + mind creates reality - stream = mmo rts fp - creation


https://mathisonian.github.io/lorenz/

scroll through structures on big computer and try to get 20 million points in changing color according to response to what person says 
make it like zork and friends - fallout 2 
prototype it with raffi and abid

cost of labor goes down till people can crowdfund a city using automated technology
35 billion - 5 dollars per person 
use data visualization to convince people that this is a good idea

half sicp - half brochure to build city


orchestrate the inevitabiltiy of success for 7 billion people as anon

start a bonfire for 7 billion MAU


university in a book

math - ai people
physics - planning people
terraform earth with arcology - management
designers = help with visualization design
engineers make diagrams or modules
molecular gastronomy by chefs
HR - jurisprudence 
everyone help make diagrams with low-code-no-code UI like shadergraph


reinvent knowledge sharing industry 
reality creation 4 a trillion dollar industry

get kids to pay more attention in class and love and respect their teachers more

teach collaboration through multiplayer editing

learn preferences w/o login 
instaloader visualizevalue --login abrahammaslowe92

everyone please add most interesting data sets imaginable including synthetic datasets like scraped amazon authors and the date and age they made their best creation which i thought was 45-60 because Jiro never stopped peaking at 96

TODO add spreadhsheet of collaborators/editors/emails/observablehq

every job is a practice for the next one so do your best and make cool modules to get the best one that i know you can get

by reading this book, we have changed your fate and you are destined for Greatness. I can see your future and i know you better than you know yourself. 

by contributing to this book you have made my dreams come true and yours too.

the point of zoox is to reuse self-driving car knowledge to enrich the next generation to make a million unicorns and lots of robotics-scientists to make AGI
cars are only the beginning, at zoox we will create armies of robots to rebuild and empower the earth

make your code more meaningful by making it literate so you remember wtf it was doing and 

this book is g-rated and meant for the advanced beginner and hidden genius within everyone but especially kindergarderners because the simpler the code the better the author because the easier it is to understanding
simplicity is the mark of true skill. 
make something worth forking and watch the world transform


start before they are conditioned by school to give up
but also inspire everyone to keep going is the goal. 

together we can reinvent the earth

we have 2500 geniuses, its the first company i came into where i felt not even average. - shel bernstein


document 3 phenomena :
client-side AI
webgpu
the MIND > GOD

together we can correct the market ineffecienes, augment human intelligence to be super-human, change cities and remove information assymetries with GNU code

keep energy positive + light

the only emotion you allow yourself to have from now on is reason and passion


visualize all mental models especially critical mass